=== mkaouer/Code-Smells-Detection-in-JavaScript/JS-CS-Detection-byExample/Dataset (ALERT 5 GB)/356782_25825532/Software Quality Assignment/jPOS-1-3-0/jpos/src/ext/org/jpos/apps/qsp/qsp-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id$ -->

<!ELEMENT qsp-config (logger*,mux*,task*,daily-task*,server*,
                      control-panel*,sequencer*,card-agent*,
		      persistent-engine*, dir-poll*)*>
<!ATTLIST qsp-config logger IDREF #IMPLIED>
<!ATTLIST qsp-config realm  CDATA #IMPLIED>
<!ATTLIST qsp-config reload CDATA #IMPLIED>

<!-- logger -->
<!ELEMENT logger (log-listener*)>
<!ATTLIST logger name ID #REQUIRED>

<!-- log-listener -->
<!ELEMENT log-listener (property*)>
<!ATTLIST log-listener class CDATA #REQUIRED>
<!ATTLIST log-listener name  CDATA #IMPLIED>

<!-- channel -->
<!ELEMENT channel (property*, filter*)*>
<!ATTLIST channel name ID #REQUIRED>
<!ATTLIST channel class CDATA #REQUIRED>
<!ATTLIST channel connect (yes|no) 'no'>
<!ATTLIST channel logger IDREF #IMPLIED>
<!ATTLIST channel realm CDATA #IMPLIED>
<!ATTLIST channel header CDATA #IMPLIED>
<!ATTLIST channel packager CDATA #IMPLIED>
<!ATTLIST channel panel IDREF #IMPLIED>
<!ATTLIST channel type (client|server) #IMPLIED>
<!ATTLIST channel timeout CDATA #IMPLIED>

<!-- filter -->
<!ELEMENT filter (property)*>
<!ATTLIST filter class CDATA #REQUIRED>
<!ATTLIST filter direction (incoming|outgoing|both) 'both'>

<!-- mux -->
<!ELEMENT mux (property*,channel,request-listener*)*>
<!ATTLIST mux name ID #REQUIRED>
<!ATTLIST mux logger IDREF #IMPLIED>
<!ATTLIST mux realm CDATA #IMPLIED>
<!ATTLIST mux connect (yes|no) 'yes'>

<!-- task -->
<!ELEMENT task (property)*>
<!ATTLIST task class CDATA #REQUIRED>
<!ATTLIST task logger IDREF #IMPLIED>
<!ATTLIST task realm CDATA #IMPLIED>
<!ATTLIST task name ID #IMPLIED>

<!-- property -->
<!ELEMENT property EMPTY>
<!ATTLIST property name  CDATA #IMPLIED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST property file  CDATA #IMPLIED>

<!-- request-listener -->
<!ELEMENT request-listener (property)*>
<!ATTLIST request-listener class CDATA #REQUIRED>
<!ATTLIST request-listener logger IDREF #IMPLIED>
<!ATTLIST request-listener realm CDATA #IMPLIED>

<!-- server  -->
<!ELEMENT server (channel,request-listener*)*>
<!ATTLIST server name ID #REQUIRED>
<!ATTLIST server port CDATA #REQUIRED>
<!ATTLIST server logger IDREF #IMPLIED>
<!ATTLIST server realm CDATA #IMPLIED>
<!ATTLIST server maxSessions CDATA #IMPLIED>
<!ATTLIST server panel IDREF #IMPLIED>

<!-- control-panel -->
<!ELEMENT control-panel (panel)*>
<!ATTLIST control-panel rows CDATA #REQUIRED>
<!ATTLIST control-panel cols CDATA #REQUIRED>

<!-- panel -->
<!ELEMENT panel EMPTY>
<!ATTLIST panel name ID #REQUIRED>

<!-- sequencer -->
<!ELEMENT sequencer (property)*>
<!ATTLIST sequencer name ID #REQUIRED>
<!ATTLIST sequencer class CDATA #REQUIRED>
<!ATTLIST sequencer logger IDREF #IMPLIED>
<!ATTLIST sequencer realm CDATA #IMPLIED>

<!-- card-agent -->
<!ELEMENT card-agent (property)*>
<!ATTLIST card-agent class CDATA #REQUIRED>
<!ATTLIST card-agent logger IDREF #IMPLIED>
<!ATTLIST card-agent realm CDATA #IMPLIED>
<!ATTLIST card-agent persistent-engine CDATA #IMPLIED>

<!-- persistent-engine -->
<!ELEMENT persistent-engine (property)*>
<!ATTLIST persistent-engine name ID #REQUIRED>
<!ATTLIST persistent-engine logger IDREF #IMPLIED>
<!ATTLIST persistent-engine realm CDATA #IMPLIED>

<!-- directory-poll -->
<!ELEMENT dir-poll (property)*>
<!ATTLIST dir-poll name ID #IMPLIED>
<!ATTLIST dir-poll path CDATA #REQUIRED>
<!ATTLIST dir-poll create (yes|no) 'no'>
<!ATTLIST dir-poll poolsize CDATA #IMPLIED>
<!ATTLIST dir-poll interval CDATA #IMPLIED>
<!ATTLIST dir-poll priorities CDATA #IMPLIED>
<!ATTLIST dir-poll processor CDATA #REQUIRED>
<!ATTLIST dir-poll logger IDREF #IMPLIED>
<!ATTLIST dir-poll realm  CDATA #IMPLIED>

<!-- daily-task -->
<!ELEMENT daily-task (property)*>
<!ATTLIST daily-task class CDATA #REQUIRED>
<!ATTLIST daily-task logger IDREF #IMPLIED>
<!ATTLIST daily-task realm CDATA #IMPLIED>
<!ATTLIST daily-task name ID #IMPLIED>
<!ATTLIST daily-task start CDATA #REQUIRED>
<!ATTLIST daily-task poolsize CDATA #IMPLIED>

=== mkaouer/Code-Smells-Detection-in-JavaScript/JS-CS-Detection-byExample/Dataset (ALERT 5 GB)/356782_25825532/Software Quality Assignment/jPOS-1_5_0/jpos/src/ext-examples/qsp/connectionpool/connection-pool.xml
<?xml version="1.0" ?>
<!--

  This QSP config creates a DB connection pool and makes it available to a task

-->

<!DOCTYPE qsp-config SYSTEM "../../../config/qsp/qsp-config.dtd"> 
<qsp-config logger="qsp" realm="qsp" reload="10000">

 <logger name="qsp">
    <log-listener class="org.jpos.util.SimpleLogListener"/>
 </logger>

  <connection-pool name="mydb" logger="qsp" realm="connection-pool">
    <property name="jdbc.driver" value="sun.jdbc.odbc.JdbcOdbcDriver" />
    <property name="jdbc.url" value="jdbc:odbc:myDSN" />
    <property name="jdbc.user" value="sa" />
    <property name="jdbc.password" value="" />
    <property name="initial-connections" value="1" />
    <property name="max-connections" value="2" />
    <property name="wait-if-busy" value="false" />
  </connection-pool>

  <task class="qsp.connectionpool.Test" connection-pool="mydb"
	 logger="qsp" realm="mytask" name="mytask">
     <property name="property1" value="value1"  />
  </task>

</qsp-config>
